---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{.Namespace}}
  name: operator-webhook-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-webhook
  labels:
    created-by: {{ .OperatorGeneratedResourcesLabelSelector | default "sriov-network-operator" }}
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - "sriovnetwork.openshift.io"
  resources:
    - "*"
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-webhook-role-binding
  labels:
    created-by: {{ .OperatorGeneratedResourcesLabelSelector | default "sriov-network-operator" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-webhook
subjects:
- kind: ServiceAccount
  name: operator-webhook-sa
  namespace: {{.Namespace}}
